#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8000" \
        cd /app/healthchecks s6-setuidgid abc /usr/sbin/uwsgi --ini uwsgi.ini
