#!/usr/bin/with-contenv bash

# define array for input values
declare -A HEATLHC_ARRAY
HEATLHC_ARRAY[SITE_ROOT]=$SITE_ROOT
HEATLHC_ARRAY[SITE_NAME]=$SITE_NAME
HEATLHC_ARRAY[DEFAULT_FROM_EMAIL]=$DEFAULT_FROM_EMAIL
HEATLHC_ARRAY[EMAIL_HOST]=$EMAIL_HOST
HEATLHC_ARRAY[EMAIL_PORT]=$EMAIL_PORT
HEATLHC_ARRAY[EMAIL_HOST_USER]=$EMAIL_HOST_USER
HEATLHC_ARRAY[EMAIL_HOST_PASSWORD]=$EMAIL_HOST_PASSWORD
HEATLHC_ARRAY[EMAIL_USE_TLS]=$EMAIL_USE_TLS

# create symlinks for settings and database files
[[ ! -f "/config/local_settings.py" ]] && \
	cp /defaults/local_settings.py /config/local_settings.py
[[ ! -L "/app/healthchecks/hc/local_settings.py" ]] && \
	ln -sf /config/local_settings.py /app/healthchecks/hc/local_settings.py
[[ ! -L "/app/healthchecks/hc.sqlite" ]] && \
	ln -sf /config/hc.sqlite /app/healthchecks/hc.sqlite

# sed in values or skip if value not set
for KEY in "${!HEATLHC_ARRAY[@]}"; do \
if [[ ${HEATLHC_ARRAY[$KEY]} == "" ]]; then \
:
else echo "$KEY" "${HEATLHC_ARRAY[$KEY]}"
fi
done

# permissions
chown -R abc:abc \
	/app/healthchecks \
	/config

cd /app/healthchecks || exit

exec \
	s6-setuidgid abc ./manage.py migrate
