#!/usr/bin/with-contenv bash

# set default values for variables
if [ -n "${SITE_ROOT}" ]; then
    BASE_URL=$(echo "${SITE_ROOT}"| awk -F[/:] '{print $4}')
fi

HC_CONF=(DEBUG EMAIL_USE_TLS SITE_ROOT SITE_NAME DEFAULT_FROM_EMAIL EMAIL_HOST EMAIL_PORT EMAIL_HOST_USER EMAIL_HOST_PASSWORD SITE_LOGO_URL ALLOWED_HOSTS)

function insert_config() {
    if grep -E "^$1 = " /config/local_settings.py; then
        sed -i "s/^$1 = .*\n\$/$1 = $2/" /config/local_settings.py
    else
        echo "$1 = $2" >> /config/local_settings.py
    fi
}

if [ ! -f "/config/local_settings.py" ] || [[ "${REGENERATE_SETTINGS}" == "True" ]]; then
    for CONF in "${HC_CONF[@]}"; do
        if [[ -n "${!CONF}" ]]; then
		if [[ "${!CONF}" == "True" ]] || [[ "${!CONF}" == "False" ]] || [[ "${!CONF:0:1}" == "[" ]]; then #booleans or arrays
			insert_config "$CONF" "${!CONF}"
                else
                        insert_config "$CONF" "\"${!CONF}\""
                fi
        fi
    done
    insert_config "CSRF_TRUSTED_ORIGINS" "[\"${BASE_URL}\"]"
fi

if [[ -z "$SECRET_KEY" ]] && ! grep "SECRET_KEY" /config/local_settings.py; then
    insert_config "SECRET_KEY" "\"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16 ; echo '')\""
fi
    

if [ ! -f "/app/healthchecks/hc/local_settings.py" ]; then
    ln -s /config/local_settings.py /app/healthchecks/hc/local_settings.py
fi

if [ ! -f "/app/healthchecks/hc.sqlite" ]; then
    ln -s /config/hc.sqlite /app/healthchecks/hc.sqlite
fi

mv /defaults/uwsgi.ini /app/healthchecks/uwsgi.ini > /dev/null 2>&1

# permissions
chown -R abc:abc \
    /app/healthchecks \
    /config

cd /app/healthchecks || exit

s6-setuidgid abc /usr/bin/python3 ./manage.py migrate

if [ -n "$SUPERUSER_EMAIL" ] && [ -n "$SUPERUSER_PASSWORD" ];
then
cat << EOF | s6-setuidgid abc python3 /app/healthchecks/manage.py shell
from django.contrib.auth.models import User;

username = 'admin';
password = '$SUPERUSER_PASSWORD';
email = '$SUPERUSER_EMAIL';

if User.objects.filter(username=username).count()==0:
    User.objects.create_superuser(username, email, password);
    print('Superuser created.');
else:
    print('Superuser creation skipped. Already exists.');
EOF
fi
